name: rick_morty_getx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.4
  dart_code_metrics_presets: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.2.2
  flutter_icons_null_safety: ^1.1.0
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true

  fonts:
    - family: Blippo
      fonts:
        - asset: fonts/blippo.ttf
 
  assets:
  - assets/logo.png