name: rick_morty_mobx_
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.6.0+1
  build_runner: ^2.4.8
  
flutter:
  uses-material-design: true

  fonts:
    - family: Blippo
      fonts:
        - asset: fonts/blippo.ttf

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_mobx: ^2.2.0+2  
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  get_it: ^7.6.7
